package pack.menu;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import pack.connexion.Connexion;
import pack.crud.Gestion_Location;
import pack.crud.Gestion_des_Biens;
import pack.crud.Gestion_des_Proprietaire;
import pack.dao.StatistiqueDao;
import pack.util.ChartUtil;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Lenovo
 */
public class MenuPrincipal extends javax.swing.JFrame {

    Connection con = Connexion.getConnection();
    private javax.swing.JFrame fenetreActive = null;

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        chargerGraphes();
        chargerTable();
    }

    public void chargerTable() {
        String[] colonnes = {"ID LOCATION", "TYPE DU BIEN", "NOM PROPRIETAIRE", "PRIX MENSUEL", "DATE DEBUT", "DATE FIN", "LOYER"};
        DefaultTableModel model = new DefaultTableModel(null, colonnes);

        String sql = "SELECT l.id_location, b.type, p.nom, b.prix_mensuel, l.date_debut, l.date_fin, l.loyer "
                + "FROM location l "
                + "JOIN bien b ON l.id_bien = b.id_bien "
                + "JOIN proprietaire p ON b.id_proprietaire = p.id_proprietaire";

        try {
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            Object[] ligne = new Object[7];

            while (rs.next()) {
                ligne[0] = rs.getInt("id_location");
                ligne[1] = rs.getString("type");
                ligne[2] = rs.getString("nom");
                ligne[3] = rs.getDouble("prix_mensuel");
                ligne[4] = rs.getDate("date_debut");
                ligne[5] = rs.getDate("date_fin");
                ligne[6] = rs.getBigDecimal("loyer"); // Utilisation de BigDecimal pour le type decimal(10,2)

                model.addRow(ligne);
            }

            jTable1.setModel(model);

        } catch (SQLException e) {
            System.err.println("Erreur lors du chargement de la table : " + e.getMessage());
        }
    }

    public void chargerGraphes() {
        try {
            StatistiqueDao dao = new StatistiqueDao();

            ChartUtil.pieChart(
                    jPanelRevenuVille,
                    "Revenus par Ville",
                    dao.revenuParVille()
            );

            ChartUtil.barChart(
                    jPanelRevenueProprietaire,
                    "Revenus par Propriétaire",
                    "Propriétaire",
                    "Montant (DH)",
                    dao.revenuParProprietaire()
            );

            ChartUtil.barChart(
                    jPanelRevenuType,
                    "Revenus par Type de Bien",
                    "Type",
                    "Montant (DH)",
                    dao.revenuParType()
            );

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelRevenuVille = new javax.swing.JPanel();
        jPanelRevenueProprietaire = new javax.swing.JPanel();
        jPanelRevenuType = new javax.swing.JPanel();
        jPanelGrideStatistique = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        GestionDesBien = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(900, 375));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dashbord RedCity IMMO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(573, 573, 573)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 2043, Short.MAX_VALUE)
                .addGap(116, 116, 116))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(56, 56, 56))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanelRevenuVille.setBackground(new java.awt.Color(153, 0, 0));
        jPanelRevenuVille.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(9, 10, 0, 0);
        getContentPane().add(jPanelRevenuVille, gridBagConstraints);

        jPanelRevenueProprietaire.setBackground(new java.awt.Color(153, 0, 0));
        jPanelRevenueProprietaire.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanelRevenueProprietaire, gridBagConstraints);

        jPanelRevenuType.setBackground(new java.awt.Color(153, 0, 0));
        jPanelRevenuType.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(9, 58, 16, 0);
        getContentPane().add(jPanelRevenuType, gridBagConstraints);

        jPanelGrideStatistique.setBackground(new java.awt.Color(153, 0, 0));
        jPanelGrideStatistique.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanelGrideStatistique.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(9, 10, 16, 0);
        getContentPane().add(jPanelGrideStatistique, gridBagConstraints);

        jMenu1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jMenu1.setText("Bien");
        jMenu1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        GestionDesBien.setText("Gestion Des Bien");
        GestionDesBien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionDesBienActionPerformed(evt);
            }
        });
        jMenu1.add(GestionDesBien);

        jMenuBar1.add(jMenu1);

        jMenu2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jMenu2.setText("Location");
        jMenu2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Gestion Location");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jMenu3.setText("Proprietaire");
        jMenu3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jMenuItem2.setText("Gestion des proprietaires");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Quitter");
        jMenu4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void GestionDesBienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionDesBienActionPerformed
        // TODO add your handling code here:
        if (fenetreActive != null) {
            fenetreActive.dispose();
        }
        Gestion_des_Biens f = new Gestion_des_Biens(this);
        fenetreActive = f;
        f.setVisible(true);
    }//GEN-LAST:event_GestionDesBienActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        if (fenetreActive != null) {
            fenetreActive.dispose();
        }
        Gestion_Location f = new Gestion_Location(this);
        fenetreActive = f;

        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        if (fenetreActive != null) {
            fenetreActive.dispose();
        }
        Gestion_des_Proprietaire f = new Gestion_des_Proprietaire(this);
        fenetreActive = f;

        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem GestionDesBien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelGrideStatistique;
    private javax.swing.JPanel jPanelRevenuType;
    private javax.swing.JPanel jPanelRevenuVille;
    private javax.swing.JPanel jPanelRevenueProprietaire;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
